Models/Tag.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace EdChannel.Models
{
    public class Tag
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }
        [Required]
        [StringLength(100)]
        public string? Title { get; set; }
        [StringLength(100)]
        [DisplayName("Title MetaTag")]
        public string? MetaTitle { get; set; }

        [Required]
        [StringLength(100)]
        public string? Slug { get; set; }

        public string? Details { get; set; }

        public virtual ICollection<ProductTag> ProductTags { get; set; } = new List<ProductTag>();

    }
}

Areas/Dashboard/Controllers/TagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EdChannel.Data;
using EdChannel.Models;

namespace EdChannel.Areas.Dashboard.Controllers
{
    [Area("Dashboard")]
    public class TagsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TagsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Dashboard/Tags
        public async Task<IActionResult> Index()
        {
              return _context.Tags != null ? 
                          View(await _context.Tags.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Tags'  is null.");
        }

        // GET: Dashboard/Tags/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // GET: Dashboard/Tags/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Dashboard/Tags/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,MetaTitle,Slug,Details")] Tag tag)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tag);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Dashboard/Tags/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags.FindAsync(id);
            if (tag == null)
            {
                return NotFound();
            }
            return View(tag);
        }

        // POST: Dashboard/Tags/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,Title,MetaTitle,Slug,Details")] Tag tag)
        {
            if (id != tag.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tag);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TagExists(tag.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tag);
        }

        // GET: Dashboard/Tags/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null || _context.Tags == null)
            {
                return NotFound();
            }

            var tag = await _context.Tags
                .FirstOrDefaultAsync(m => m.Id == id);
            if (tag == null)
            {
                return NotFound();
            }

            return View(tag);
        }

        // POST: Dashboard/Tags/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            if (_context.Tags == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Tags'  is null.");
            }
            var tag = await _context.Tags.FindAsync(id);
            if (tag != null)
            {
                _context.Tags.Remove(tag);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TagExists(long id)
        {
          return (_context.Tags?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Areas/Dashboard/Views/Tags/Create.cshtml
@model EdChannel.Models.Tag

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";
}


<div class="content">
    <div class="page-header">
        <div class="page-title">
            <h4>Add Category</h4>
            <h6>Create new Category</h6>
        </div>
        <div class="page-btn">
            <a asp-action="Index" class="btn btn-added">
                <img src="~/img/icons/return1.svg" class="me-2" alt="img">Back to list
            </a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <form asp-action="Create">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="MetaTitle" class="control-label"></label>
                            <input asp-for="MetaTitle" class="form-control" />
                            <span asp-validation-for="MetaTitle" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Slug" class="control-label"></label>
                            <input asp-for="Slug" class="form-control" />
                            <span asp-validation-for="Slug" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Details" class="control-label"></label>
                            <input asp-for="Details" class="form-control" />
                            <span asp-validation-for="Details" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Dashboard/Views/Tags/Delete.cshtml
@model EdChannel.Models.Tag

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Tag</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slug)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Slug)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Areas/Dashboard/Views/Tags/Details.cshtml
@model EdChannel.Models.Tag

@{
    ViewData["Title"] = "Details";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Tag</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MetaTitle)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MetaTitle)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Slug)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Slug)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Details)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Details)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Areas/Dashboard/Views/Tags/Edit.cshtml
@model EdChannel.Models.Tag

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";
}


<div class="content">
    <div class="page-header">
        <div class="page-title">
            <h4>Add Tag</h4>
            <h6>Update tag</h6>
        </div>
        <div class="page-btn">
            <a asp-action="Index" class="btn btn-added">
                <img src="~/img/icons/return1.svg" class="me-2" alt="img">Back to list
            </a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <form asp-action="Edit">
                        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                        <input type="hidden" asp-for="Id" />
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="MetaTitle" class="control-label"></label>
                            <input asp-for="MetaTitle" class="form-control" />
                            <span asp-validation-for="MetaTitle" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Slug" class="control-label"></label>
                            <input asp-for="Slug" class="form-control" />
                            <span asp-validation-for="Slug" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Details" class="control-label"></label>
                            <input asp-for="Details" class="form-control" />
                            <span asp-validation-for="Details" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Save" class="btn btn-primary" />
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Areas/Dashboard/Views/Tags/Index.cshtml
@model IEnumerable<EdChannel.Models.Tag>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Dashboard/Views/Shared/_Layout.cshtml";
}

<partial name="~/Areas/Dashboard/Views/Shared/_Notification.cshtml" />

<div class="content">
    <div class="page-header">
        <div class="page-title">
            <h4>Product Tag list</h4>
            <h6>View/Search product Tag</h6>
        </div>
        <div class="page-btn">
            <a asp-action="Create" class="btn btn-added">
                <img src="~/img/icons/plus.svg" class="me-1" alt="img">Add Tag
            </a>
        </div>
    </div>

    <div class="card">
        <div class="card-body">
            <div class="table-top">
                <div class="search-set">
                    <div class="search-path">
                        <a class="btn btn-filter" id="filter_search">
                            <img src="~/img/icons/filter.svg" alt="img">
                            <span><img src="~/img/icons/closes.svg" alt="img"></span>
                        </a>
                    </div>
                    <div class="search-input">
                        <a class="btn btn-searchset"><img src="~/img/icons/search-white.svg" alt="img"></a>
                        <div id="DataTables_Table_0_filter" class="dataTables_filter"><label> <input type="search" class="form-control form-control-sm" placeholder="Search..." aria-controls="DataTables_Table_0"></label></div>
                    </div>
                </div>
                <div class="wordset">
                    <ul>
                        <li>
                            <a data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="pdf" aria-label="pdf"><img src="~/img/icons/pdf.svg" alt="img"></a>
                        </li>
                        <li>
                            <a data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="excel" aria-label="excel"><img src="~/img/icons/excel.svg" alt="img"></a>
                        </li>
                        <li>
                            <a data-bs-toggle="tooltip" data-bs-placement="top" title="" data-bs-original-title="print" aria-label="print"><img src="~/img/icons/printer.svg" alt="img"></a>
                        </li>
                    </ul>
                </div>
            </div>

            <div class="table-responsive">
                <div id="DataTables_Table_0_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                    <table class="table datanew dataTable no-footer" id="DataTables_Table_0" role="grid" aria-describedby="DataTables_Table_0_info">
                        <thead>
                            <tr role="row">
                                @* <th class="sorting_asc" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-sort="ascending" aria-label="
:                                   activate to sort column descending" style="width: 79.6625px;">
                                    <label class="checkboxs">
                                        <input type="checkbox" id="select-all">
                                        <span class="checkmarks"></span>
                                    </label>
                                </th> *@
                                <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="@Html.DisplayNameFor(model => model.Title) name: activate to sort column ascending" style="width: 370px;">@Html.DisplayNameFor(model => model.Title)</th>
                                <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="@Html.DisplayNameFor(model => model.MetaTitle): activate to sort column ascending" style="width: 252.7px;">@Html.DisplayNameFor(model => model.MetaTitle)</th>
                                <th class="sorting" tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="@Html.DisplayNameFor(model => model.Details): activate to sort column ascending" style="width: 335.775px;">@Html.DisplayNameFor(model => model.Details)</th>
                                <th tabindex="0" aria-controls="DataTables_Table_0" rowspan="1" colspan="1" aria-label="Action: activate to sort column ascending" style="width: 150.062px;">Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                int count = 0;
                            }
                            @foreach (var item in Model)
                            {

                                <tr class="@(count % 2 == 0 ? "even" : "old")">
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Title)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.MetaTitle)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Details)
                                    </td>
                                    <td class="">
                                        @* <a asp-action="Details" asp-route-id="@item.Id" style="margin-right: 15px;">
                                            <img src="~/img/icons/eye.svg" style="width: 22px" alt="img" data-bs-original-title="Details" aria-label="Details" data-bs-toggle="tooltip">
                                        </a> *@
                                        <a asp-action="Edit" asp-route-id="@item.Id" style="margin-right: 15px;">
                                            <img src="~/img/icons/edit.svg" alt="img" data-bs-original-title="Edit" aria-label="Edit" data-bs-toggle="tooltip">
                                        </a>
                                        <form asp-controller="Tags" asp-action="Delete" asp-route-id="@item.Id" class="d-inline">
                                            <input id="btnDelete-@item.Id" type="submit" name="@item.Id" value="Delete" class="btn btn-danger d-none" />
                                            <label for="btnDelete-@item.Id">
                                                <img src="~/img/icons/delete.svg" alt="img" data-bs-toggle="tooltip" data-bs-original-title="Delete" aria-label="Delete">
                                            </label>
                                        </form>
                                    </td>
                                </tr>
                                count++;
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

</div>